### ISSUE TITLE
Slider comments

### ISSUE THREAD

**Issue by sffr-dev** [AlekseiZhukov/FR6-TURNKEY-REPAIR#1]
1. https://github.com/AlekseiZhukov/FR6-TURNKEY-REPAIR/blob/c76b8ad602106f957d6cedc179269c32942f2e77/src/script.js#L82-L99
Вот этот кусок можно сделать более универсальным, если пройтись методом `forEach` по коллекциям `pointList` и `linkList` и повесить обработчики на элементы, пользуясь индексами элементов. Тогда можно будет убрать еще и этот кусок 
https://github.com/AlekseiZhukov/FR6-TURNKEY-REPAIR/blob/c76b8ad602106f957d6cedc179269c32942f2e77/src/script.js#L34-L39
и id-шники у элементов

2. При именовании функций держите в голове правило, что функция должна описывать **действие** (setInnerText, setNextSlide), а переменная должна описывать **сущность**

**Comment by AlekseiZhukov** [comment]
Done
